// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: hpx.proto

#include "hpx.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace HpXVer {
PROTOBUF_CONSTEXPR PendingItem::PendingItem(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_._has_bits_)*/{}
  , /*decltype(_impl_._cached_size_)*/{}
  , /*decltype(_impl_.price_)*/0
  , /*decltype(_impl_.volume_)*/0} {}
struct PendingItemDefaultTypeInternal {
  PROTOBUF_CONSTEXPR PendingItemDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~PendingItemDefaultTypeInternal() {}
  union {
    PendingItem _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PendingItemDefaultTypeInternal _PendingItem_default_instance_;
PROTOBUF_CONSTEXPR PriceInfo::PriceInfo(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_._has_bits_)*/{}
  , /*decltype(_impl_._cached_size_)*/{}
  , /*decltype(_impl_.pending_buy_volume_dict_)*/{}
  , /*decltype(_impl_.pending_sell_volume_dict_)*/{}
  , /*decltype(_impl_.instrument_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.force_withdraw_buy_price_)*/0
  , /*decltype(_impl_.force_withdraw_sell_price_)*/0} {}
struct PriceInfoDefaultTypeInternal {
  PROTOBUF_CONSTEXPR PriceInfoDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~PriceInfoDefaultTypeInternal() {}
  union {
    PriceInfo _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PriceInfoDefaultTypeInternal _PriceInfo_default_instance_;
PROTOBUF_CONSTEXPR HpxSubProto::HpxSubProto(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_._has_bits_)*/{}
  , /*decltype(_impl_._cached_size_)*/{}
  , /*decltype(_impl_.key_suffix_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.managed_suffix_)*/0} {}
struct HpxSubProtoDefaultTypeInternal {
  PROTOBUF_CONSTEXPR HpxSubProtoDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~HpxSubProtoDefaultTypeInternal() {}
  union {
    HpxSubProto _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 HpxSubProtoDefaultTypeInternal _HpxSubProto_default_instance_;
PROTOBUF_CONSTEXPR TheoProgress::TheoProgress(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_._has_bits_)*/{}
  , /*decltype(_impl_._cached_size_)*/{}
  , /*decltype(_impl_.instrument_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.key_suffix_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.value_)*/0
  , /*decltype(_impl_.managed_suffix_)*/0} {}
struct TheoProgressDefaultTypeInternal {
  PROTOBUF_CONSTEXPR TheoProgressDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~TheoProgressDefaultTypeInternal() {}
  union {
    TheoProgress _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 TheoProgressDefaultTypeInternal _TheoProgress_default_instance_;
PROTOBUF_CONSTEXPR HpxPriceProto::HpxPriceProto(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.items_)*/{}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct HpxPriceProtoDefaultTypeInternal {
  PROTOBUF_CONSTEXPR HpxPriceProtoDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~HpxPriceProtoDefaultTypeInternal() {}
  union {
    HpxPriceProto _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 HpxPriceProtoDefaultTypeInternal _HpxPriceProto_default_instance_;
PROTOBUF_CONSTEXPR HpxTheoProgressProto::HpxTheoProgressProto(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.items_)*/{}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct HpxTheoProgressProtoDefaultTypeInternal {
  PROTOBUF_CONSTEXPR HpxTheoProgressProtoDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~HpxTheoProgressProtoDefaultTypeInternal() {}
  union {
    HpxTheoProgressProto _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 HpxTheoProgressProtoDefaultTypeInternal _HpxTheoProgressProto_default_instance_;
}  // namespace HpXVer
static ::_pb::Metadata file_level_metadata_hpx_2eproto[6];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_hpx_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_hpx_2eproto = nullptr;

const uint32_t TableStruct_hpx_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  PROTOBUF_FIELD_OFFSET(::HpXVer::PendingItem, _impl_._has_bits_),
  PROTOBUF_FIELD_OFFSET(::HpXVer::PendingItem, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::HpXVer::PendingItem, _impl_.price_),
  PROTOBUF_FIELD_OFFSET(::HpXVer::PendingItem, _impl_.volume_),
  0,
  1,
  PROTOBUF_FIELD_OFFSET(::HpXVer::PriceInfo, _impl_._has_bits_),
  PROTOBUF_FIELD_OFFSET(::HpXVer::PriceInfo, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::HpXVer::PriceInfo, _impl_.instrument_),
  PROTOBUF_FIELD_OFFSET(::HpXVer::PriceInfo, _impl_.force_withdraw_buy_price_),
  PROTOBUF_FIELD_OFFSET(::HpXVer::PriceInfo, _impl_.force_withdraw_sell_price_),
  PROTOBUF_FIELD_OFFSET(::HpXVer::PriceInfo, _impl_.pending_buy_volume_dict_),
  PROTOBUF_FIELD_OFFSET(::HpXVer::PriceInfo, _impl_.pending_sell_volume_dict_),
  0,
  1,
  2,
  ~0u,
  ~0u,
  PROTOBUF_FIELD_OFFSET(::HpXVer::HpxSubProto, _impl_._has_bits_),
  PROTOBUF_FIELD_OFFSET(::HpXVer::HpxSubProto, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::HpXVer::HpxSubProto, _impl_.managed_suffix_),
  PROTOBUF_FIELD_OFFSET(::HpXVer::HpxSubProto, _impl_.key_suffix_),
  1,
  0,
  PROTOBUF_FIELD_OFFSET(::HpXVer::TheoProgress, _impl_._has_bits_),
  PROTOBUF_FIELD_OFFSET(::HpXVer::TheoProgress, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::HpXVer::TheoProgress, _impl_.instrument_),
  PROTOBUF_FIELD_OFFSET(::HpXVer::TheoProgress, _impl_.managed_suffix_),
  PROTOBUF_FIELD_OFFSET(::HpXVer::TheoProgress, _impl_.key_suffix_),
  PROTOBUF_FIELD_OFFSET(::HpXVer::TheoProgress, _impl_.value_),
  0,
  3,
  1,
  2,
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::HpXVer::HpxPriceProto, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::HpXVer::HpxPriceProto, _impl_.items_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::HpXVer::HpxTheoProgressProto, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::HpXVer::HpxTheoProgressProto, _impl_.items_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, 8, -1, sizeof(::HpXVer::PendingItem)},
  { 10, 21, -1, sizeof(::HpXVer::PriceInfo)},
  { 26, 34, -1, sizeof(::HpXVer::HpxSubProto)},
  { 36, 46, -1, sizeof(::HpXVer::TheoProgress)},
  { 50, -1, -1, sizeof(::HpXVer::HpxPriceProto)},
  { 57, -1, -1, sizeof(::HpXVer::HpxTheoProgressProto)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::HpXVer::_PendingItem_default_instance_._instance,
  &::HpXVer::_PriceInfo_default_instance_._instance,
  &::HpXVer::_HpxSubProto_default_instance_._instance,
  &::HpXVer::_TheoProgress_default_instance_._instance,
  &::HpXVer::_HpxPriceProto_default_instance_._instance,
  &::HpXVer::_HpxTheoProgressProto_default_instance_._instance,
};

const char descriptor_table_protodef_hpx_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\thpx.proto\022\006HpXVer\",\n\013PendingItem\022\r\n\005pr"
  "ice\030\001 \001(\001\022\016\n\006volume\030\002 \001(\005\"\321\001\n\tPriceInfo\022"
  "\022\n\ninstrument\030\001 \001(\t\022 \n\030force_withdraw_bu"
  "y_price\030\002 \001(\001\022!\n\031force_withdraw_sell_pri"
  "ce\030\003 \001(\001\0224\n\027pending_buy_volume_dict\030\004 \003("
  "\0132\023.HpXVer.PendingItem\0225\n\030pending_sell_v"
  "olume_dict\030\005 \003(\0132\023.HpXVer.PendingItem\"9\n"
  "\013HpxSubProto\022\026\n\016managed_suffix\030\001 \001(\005\022\022\n\n"
  "key_suffix\030\002 \001(\t\"]\n\014TheoProgress\022\022\n\ninst"
  "rument\030\001 \001(\t\022\026\n\016managed_suffix\030\002 \001(\005\022\022\n\n"
  "key_suffix\030\003 \001(\t\022\r\n\005value\030\004 \001(\001\"1\n\rHpxPr"
  "iceProto\022 \n\005items\030\001 \003(\0132\021.HpXVer.PriceIn"
  "fo\";\n\024HpxTheoProgressProto\022#\n\005items\030\001 \003("
  "\0132\024.HpXVer.TheoProgress"
  ;
static ::_pbi::once_flag descriptor_table_hpx_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_hpx_2eproto = {
    false, false, 543, descriptor_table_protodef_hpx_2eproto,
    "hpx.proto",
    &descriptor_table_hpx_2eproto_once, nullptr, 0, 6,
    schemas, file_default_instances, TableStruct_hpx_2eproto::offsets,
    file_level_metadata_hpx_2eproto, file_level_enum_descriptors_hpx_2eproto,
    file_level_service_descriptors_hpx_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_hpx_2eproto_getter() {
  return &descriptor_table_hpx_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_hpx_2eproto(&descriptor_table_hpx_2eproto);
namespace HpXVer {

// ===================================================================

class PendingItem::_Internal {
 public:
  using HasBits = decltype(std::declval<PendingItem>()._impl_._has_bits_);
  static void set_has_price(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
  static void set_has_volume(HasBits* has_bits) {
    (*has_bits)[0] |= 2u;
  }
};

PendingItem::PendingItem(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:HpXVer.PendingItem)
}
PendingItem::PendingItem(const PendingItem& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  PendingItem* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){from._impl_._has_bits_}
    , /*decltype(_impl_._cached_size_)*/{}
    , decltype(_impl_.price_){}
    , decltype(_impl_.volume_){}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::memcpy(&_impl_.price_, &from._impl_.price_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.volume_) -
    reinterpret_cast<char*>(&_impl_.price_)) + sizeof(_impl_.volume_));
  // @@protoc_insertion_point(copy_constructor:HpXVer.PendingItem)
}

inline void PendingItem::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){}
    , /*decltype(_impl_._cached_size_)*/{}
    , decltype(_impl_.price_){0}
    , decltype(_impl_.volume_){0}
  };
}

PendingItem::~PendingItem() {
  // @@protoc_insertion_point(destructor:HpXVer.PendingItem)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void PendingItem::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void PendingItem::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void PendingItem::Clear() {
// @@protoc_insertion_point(message_clear_start:HpXVer.PendingItem)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    ::memset(&_impl_.price_, 0, static_cast<size_t>(
        reinterpret_cast<char*>(&_impl_.volume_) -
        reinterpret_cast<char*>(&_impl_.price_)) + sizeof(_impl_.volume_));
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* PendingItem::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  _Internal::HasBits has_bits{};
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // optional double price = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 9)) {
          _Internal::set_has_price(&has_bits);
          _impl_.price_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else
          goto handle_unusual;
        continue;
      // optional int32 volume = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          _Internal::set_has_volume(&has_bits);
          _impl_.volume_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  _impl_._has_bits_.Or(has_bits);
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* PendingItem::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:HpXVer.PendingItem)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  // optional double price = 1;
  if (cached_has_bits & 0x00000001u) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteDoubleToArray(1, this->_internal_price(), target);
  }

  // optional int32 volume = 2;
  if (cached_has_bits & 0x00000002u) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(2, this->_internal_volume(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:HpXVer.PendingItem)
  return target;
}

size_t PendingItem::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:HpXVer.PendingItem)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    // optional double price = 1;
    if (cached_has_bits & 0x00000001u) {
      total_size += 1 + 8;
    }

    // optional int32 volume = 2;
    if (cached_has_bits & 0x00000002u) {
      total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_volume());
    }

  }
  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData PendingItem::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    PendingItem::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*PendingItem::GetClassData() const { return &_class_data_; }


void PendingItem::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<PendingItem*>(&to_msg);
  auto& from = static_cast<const PendingItem&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:HpXVer.PendingItem)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    if (cached_has_bits & 0x00000001u) {
      _this->_impl_.price_ = from._impl_.price_;
    }
    if (cached_has_bits & 0x00000002u) {
      _this->_impl_.volume_ = from._impl_.volume_;
    }
    _this->_impl_._has_bits_[0] |= cached_has_bits;
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void PendingItem::CopyFrom(const PendingItem& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:HpXVer.PendingItem)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool PendingItem::IsInitialized() const {
  return true;
}

void PendingItem::InternalSwap(PendingItem* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(PendingItem, _impl_.volume_)
      + sizeof(PendingItem::_impl_.volume_)
      - PROTOBUF_FIELD_OFFSET(PendingItem, _impl_.price_)>(
          reinterpret_cast<char*>(&_impl_.price_),
          reinterpret_cast<char*>(&other->_impl_.price_));
}

::PROTOBUF_NAMESPACE_ID::Metadata PendingItem::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_hpx_2eproto_getter, &descriptor_table_hpx_2eproto_once,
      file_level_metadata_hpx_2eproto[0]);
}

// ===================================================================

class PriceInfo::_Internal {
 public:
  using HasBits = decltype(std::declval<PriceInfo>()._impl_._has_bits_);
  static void set_has_instrument(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
  static void set_has_force_withdraw_buy_price(HasBits* has_bits) {
    (*has_bits)[0] |= 2u;
  }
  static void set_has_force_withdraw_sell_price(HasBits* has_bits) {
    (*has_bits)[0] |= 4u;
  }
};

PriceInfo::PriceInfo(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:HpXVer.PriceInfo)
}
PriceInfo::PriceInfo(const PriceInfo& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  PriceInfo* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){from._impl_._has_bits_}
    , /*decltype(_impl_._cached_size_)*/{}
    , decltype(_impl_.pending_buy_volume_dict_){from._impl_.pending_buy_volume_dict_}
    , decltype(_impl_.pending_sell_volume_dict_){from._impl_.pending_sell_volume_dict_}
    , decltype(_impl_.instrument_){}
    , decltype(_impl_.force_withdraw_buy_price_){}
    , decltype(_impl_.force_withdraw_sell_price_){}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.instrument_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.instrument_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (from._internal_has_instrument()) {
    _this->_impl_.instrument_.Set(from._internal_instrument(), 
      _this->GetArenaForAllocation());
  }
  ::memcpy(&_impl_.force_withdraw_buy_price_, &from._impl_.force_withdraw_buy_price_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.force_withdraw_sell_price_) -
    reinterpret_cast<char*>(&_impl_.force_withdraw_buy_price_)) + sizeof(_impl_.force_withdraw_sell_price_));
  // @@protoc_insertion_point(copy_constructor:HpXVer.PriceInfo)
}

inline void PriceInfo::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){}
    , /*decltype(_impl_._cached_size_)*/{}
    , decltype(_impl_.pending_buy_volume_dict_){arena}
    , decltype(_impl_.pending_sell_volume_dict_){arena}
    , decltype(_impl_.instrument_){}
    , decltype(_impl_.force_withdraw_buy_price_){0}
    , decltype(_impl_.force_withdraw_sell_price_){0}
  };
  _impl_.instrument_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.instrument_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

PriceInfo::~PriceInfo() {
  // @@protoc_insertion_point(destructor:HpXVer.PriceInfo)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void PriceInfo::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.pending_buy_volume_dict_.~RepeatedPtrField();
  _impl_.pending_sell_volume_dict_.~RepeatedPtrField();
  _impl_.instrument_.Destroy();
}

void PriceInfo::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void PriceInfo::Clear() {
// @@protoc_insertion_point(message_clear_start:HpXVer.PriceInfo)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.pending_buy_volume_dict_.Clear();
  _impl_.pending_sell_volume_dict_.Clear();
  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    _impl_.instrument_.ClearNonDefaultToEmpty();
  }
  if (cached_has_bits & 0x00000006u) {
    ::memset(&_impl_.force_withdraw_buy_price_, 0, static_cast<size_t>(
        reinterpret_cast<char*>(&_impl_.force_withdraw_sell_price_) -
        reinterpret_cast<char*>(&_impl_.force_withdraw_buy_price_)) + sizeof(_impl_.force_withdraw_sell_price_));
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* PriceInfo::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  _Internal::HasBits has_bits{};
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // optional string instrument = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          auto str = _internal_mutable_instrument();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          #ifndef NDEBUG
          ::_pbi::VerifyUTF8(str, "HpXVer.PriceInfo.instrument");
          #endif  // !NDEBUG
        } else
          goto handle_unusual;
        continue;
      // optional double force_withdraw_buy_price = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 17)) {
          _Internal::set_has_force_withdraw_buy_price(&has_bits);
          _impl_.force_withdraw_buy_price_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else
          goto handle_unusual;
        continue;
      // optional double force_withdraw_sell_price = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 25)) {
          _Internal::set_has_force_withdraw_sell_price(&has_bits);
          _impl_.force_withdraw_sell_price_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else
          goto handle_unusual;
        continue;
      // repeated .HpXVer.PendingItem pending_buy_volume_dict = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 34)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_pending_buy_volume_dict(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<34>(ptr));
        } else
          goto handle_unusual;
        continue;
      // repeated .HpXVer.PendingItem pending_sell_volume_dict = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 42)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_pending_sell_volume_dict(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<42>(ptr));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  _impl_._has_bits_.Or(has_bits);
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* PriceInfo::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:HpXVer.PriceInfo)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  // optional string instrument = 1;
  if (cached_has_bits & 0x00000001u) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::VerifyUTF8StringNamedField(
      this->_internal_instrument().data(), static_cast<int>(this->_internal_instrument().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::SERIALIZE,
      "HpXVer.PriceInfo.instrument");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_instrument(), target);
  }

  // optional double force_withdraw_buy_price = 2;
  if (cached_has_bits & 0x00000002u) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteDoubleToArray(2, this->_internal_force_withdraw_buy_price(), target);
  }

  // optional double force_withdraw_sell_price = 3;
  if (cached_has_bits & 0x00000004u) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteDoubleToArray(3, this->_internal_force_withdraw_sell_price(), target);
  }

  // repeated .HpXVer.PendingItem pending_buy_volume_dict = 4;
  for (unsigned i = 0,
      n = static_cast<unsigned>(this->_internal_pending_buy_volume_dict_size()); i < n; i++) {
    const auto& repfield = this->_internal_pending_buy_volume_dict(i);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
        InternalWriteMessage(4, repfield, repfield.GetCachedSize(), target, stream);
  }

  // repeated .HpXVer.PendingItem pending_sell_volume_dict = 5;
  for (unsigned i = 0,
      n = static_cast<unsigned>(this->_internal_pending_sell_volume_dict_size()); i < n; i++) {
    const auto& repfield = this->_internal_pending_sell_volume_dict(i);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
        InternalWriteMessage(5, repfield, repfield.GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:HpXVer.PriceInfo)
  return target;
}

size_t PriceInfo::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:HpXVer.PriceInfo)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .HpXVer.PendingItem pending_buy_volume_dict = 4;
  total_size += 1UL * this->_internal_pending_buy_volume_dict_size();
  for (const auto& msg : this->_impl_.pending_buy_volume_dict_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  // repeated .HpXVer.PendingItem pending_sell_volume_dict = 5;
  total_size += 1UL * this->_internal_pending_sell_volume_dict_size();
  for (const auto& msg : this->_impl_.pending_sell_volume_dict_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000007u) {
    // optional string instrument = 1;
    if (cached_has_bits & 0x00000001u) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
          this->_internal_instrument());
    }

    // optional double force_withdraw_buy_price = 2;
    if (cached_has_bits & 0x00000002u) {
      total_size += 1 + 8;
    }

    // optional double force_withdraw_sell_price = 3;
    if (cached_has_bits & 0x00000004u) {
      total_size += 1 + 8;
    }

  }
  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData PriceInfo::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    PriceInfo::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*PriceInfo::GetClassData() const { return &_class_data_; }


void PriceInfo::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<PriceInfo*>(&to_msg);
  auto& from = static_cast<const PriceInfo&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:HpXVer.PriceInfo)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_impl_.pending_buy_volume_dict_.MergeFrom(from._impl_.pending_buy_volume_dict_);
  _this->_impl_.pending_sell_volume_dict_.MergeFrom(from._impl_.pending_sell_volume_dict_);
  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x00000007u) {
    if (cached_has_bits & 0x00000001u) {
      _this->_internal_set_instrument(from._internal_instrument());
    }
    if (cached_has_bits & 0x00000002u) {
      _this->_impl_.force_withdraw_buy_price_ = from._impl_.force_withdraw_buy_price_;
    }
    if (cached_has_bits & 0x00000004u) {
      _this->_impl_.force_withdraw_sell_price_ = from._impl_.force_withdraw_sell_price_;
    }
    _this->_impl_._has_bits_[0] |= cached_has_bits;
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void PriceInfo::CopyFrom(const PriceInfo& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:HpXVer.PriceInfo)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool PriceInfo::IsInitialized() const {
  return true;
}

void PriceInfo::InternalSwap(PriceInfo* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  _impl_.pending_buy_volume_dict_.InternalSwap(&other->_impl_.pending_buy_volume_dict_);
  _impl_.pending_sell_volume_dict_.InternalSwap(&other->_impl_.pending_sell_volume_dict_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.instrument_, lhs_arena,
      &other->_impl_.instrument_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(PriceInfo, _impl_.force_withdraw_sell_price_)
      + sizeof(PriceInfo::_impl_.force_withdraw_sell_price_)
      - PROTOBUF_FIELD_OFFSET(PriceInfo, _impl_.force_withdraw_buy_price_)>(
          reinterpret_cast<char*>(&_impl_.force_withdraw_buy_price_),
          reinterpret_cast<char*>(&other->_impl_.force_withdraw_buy_price_));
}

::PROTOBUF_NAMESPACE_ID::Metadata PriceInfo::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_hpx_2eproto_getter, &descriptor_table_hpx_2eproto_once,
      file_level_metadata_hpx_2eproto[1]);
}

// ===================================================================

class HpxSubProto::_Internal {
 public:
  using HasBits = decltype(std::declval<HpxSubProto>()._impl_._has_bits_);
  static void set_has_managed_suffix(HasBits* has_bits) {
    (*has_bits)[0] |= 2u;
  }
  static void set_has_key_suffix(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
};

HpxSubProto::HpxSubProto(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:HpXVer.HpxSubProto)
}
HpxSubProto::HpxSubProto(const HpxSubProto& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  HpxSubProto* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){from._impl_._has_bits_}
    , /*decltype(_impl_._cached_size_)*/{}
    , decltype(_impl_.key_suffix_){}
    , decltype(_impl_.managed_suffix_){}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.key_suffix_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.key_suffix_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (from._internal_has_key_suffix()) {
    _this->_impl_.key_suffix_.Set(from._internal_key_suffix(), 
      _this->GetArenaForAllocation());
  }
  _this->_impl_.managed_suffix_ = from._impl_.managed_suffix_;
  // @@protoc_insertion_point(copy_constructor:HpXVer.HpxSubProto)
}

inline void HpxSubProto::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){}
    , /*decltype(_impl_._cached_size_)*/{}
    , decltype(_impl_.key_suffix_){}
    , decltype(_impl_.managed_suffix_){0}
  };
  _impl_.key_suffix_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.key_suffix_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

HpxSubProto::~HpxSubProto() {
  // @@protoc_insertion_point(destructor:HpXVer.HpxSubProto)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void HpxSubProto::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.key_suffix_.Destroy();
}

void HpxSubProto::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void HpxSubProto::Clear() {
// @@protoc_insertion_point(message_clear_start:HpXVer.HpxSubProto)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    _impl_.key_suffix_.ClearNonDefaultToEmpty();
  }
  _impl_.managed_suffix_ = 0;
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* HpxSubProto::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  _Internal::HasBits has_bits{};
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // optional int32 managed_suffix = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _Internal::set_has_managed_suffix(&has_bits);
          _impl_.managed_suffix_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // optional string key_suffix = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          auto str = _internal_mutable_key_suffix();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          #ifndef NDEBUG
          ::_pbi::VerifyUTF8(str, "HpXVer.HpxSubProto.key_suffix");
          #endif  // !NDEBUG
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  _impl_._has_bits_.Or(has_bits);
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* HpxSubProto::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:HpXVer.HpxSubProto)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  // optional int32 managed_suffix = 1;
  if (cached_has_bits & 0x00000002u) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(1, this->_internal_managed_suffix(), target);
  }

  // optional string key_suffix = 2;
  if (cached_has_bits & 0x00000001u) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::VerifyUTF8StringNamedField(
      this->_internal_key_suffix().data(), static_cast<int>(this->_internal_key_suffix().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::SERIALIZE,
      "HpXVer.HpxSubProto.key_suffix");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_key_suffix(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:HpXVer.HpxSubProto)
  return target;
}

size_t HpxSubProto::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:HpXVer.HpxSubProto)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    // optional string key_suffix = 2;
    if (cached_has_bits & 0x00000001u) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
          this->_internal_key_suffix());
    }

    // optional int32 managed_suffix = 1;
    if (cached_has_bits & 0x00000002u) {
      total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_managed_suffix());
    }

  }
  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData HpxSubProto::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    HpxSubProto::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*HpxSubProto::GetClassData() const { return &_class_data_; }


void HpxSubProto::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<HpxSubProto*>(&to_msg);
  auto& from = static_cast<const HpxSubProto&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:HpXVer.HpxSubProto)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    if (cached_has_bits & 0x00000001u) {
      _this->_internal_set_key_suffix(from._internal_key_suffix());
    }
    if (cached_has_bits & 0x00000002u) {
      _this->_impl_.managed_suffix_ = from._impl_.managed_suffix_;
    }
    _this->_impl_._has_bits_[0] |= cached_has_bits;
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void HpxSubProto::CopyFrom(const HpxSubProto& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:HpXVer.HpxSubProto)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool HpxSubProto::IsInitialized() const {
  return true;
}

void HpxSubProto::InternalSwap(HpxSubProto* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.key_suffix_, lhs_arena,
      &other->_impl_.key_suffix_, rhs_arena
  );
  swap(_impl_.managed_suffix_, other->_impl_.managed_suffix_);
}

::PROTOBUF_NAMESPACE_ID::Metadata HpxSubProto::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_hpx_2eproto_getter, &descriptor_table_hpx_2eproto_once,
      file_level_metadata_hpx_2eproto[2]);
}

// ===================================================================

class TheoProgress::_Internal {
 public:
  using HasBits = decltype(std::declval<TheoProgress>()._impl_._has_bits_);
  static void set_has_instrument(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
  static void set_has_managed_suffix(HasBits* has_bits) {
    (*has_bits)[0] |= 8u;
  }
  static void set_has_key_suffix(HasBits* has_bits) {
    (*has_bits)[0] |= 2u;
  }
  static void set_has_value(HasBits* has_bits) {
    (*has_bits)[0] |= 4u;
  }
};

TheoProgress::TheoProgress(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:HpXVer.TheoProgress)
}
TheoProgress::TheoProgress(const TheoProgress& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  TheoProgress* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){from._impl_._has_bits_}
    , /*decltype(_impl_._cached_size_)*/{}
    , decltype(_impl_.instrument_){}
    , decltype(_impl_.key_suffix_){}
    , decltype(_impl_.value_){}
    , decltype(_impl_.managed_suffix_){}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.instrument_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.instrument_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (from._internal_has_instrument()) {
    _this->_impl_.instrument_.Set(from._internal_instrument(), 
      _this->GetArenaForAllocation());
  }
  _impl_.key_suffix_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.key_suffix_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (from._internal_has_key_suffix()) {
    _this->_impl_.key_suffix_.Set(from._internal_key_suffix(), 
      _this->GetArenaForAllocation());
  }
  ::memcpy(&_impl_.value_, &from._impl_.value_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.managed_suffix_) -
    reinterpret_cast<char*>(&_impl_.value_)) + sizeof(_impl_.managed_suffix_));
  // @@protoc_insertion_point(copy_constructor:HpXVer.TheoProgress)
}

inline void TheoProgress::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){}
    , /*decltype(_impl_._cached_size_)*/{}
    , decltype(_impl_.instrument_){}
    , decltype(_impl_.key_suffix_){}
    , decltype(_impl_.value_){0}
    , decltype(_impl_.managed_suffix_){0}
  };
  _impl_.instrument_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.instrument_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.key_suffix_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.key_suffix_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

TheoProgress::~TheoProgress() {
  // @@protoc_insertion_point(destructor:HpXVer.TheoProgress)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void TheoProgress::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.instrument_.Destroy();
  _impl_.key_suffix_.Destroy();
}

void TheoProgress::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void TheoProgress::Clear() {
// @@protoc_insertion_point(message_clear_start:HpXVer.TheoProgress)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    if (cached_has_bits & 0x00000001u) {
      _impl_.instrument_.ClearNonDefaultToEmpty();
    }
    if (cached_has_bits & 0x00000002u) {
      _impl_.key_suffix_.ClearNonDefaultToEmpty();
    }
  }
  if (cached_has_bits & 0x0000000cu) {
    ::memset(&_impl_.value_, 0, static_cast<size_t>(
        reinterpret_cast<char*>(&_impl_.managed_suffix_) -
        reinterpret_cast<char*>(&_impl_.value_)) + sizeof(_impl_.managed_suffix_));
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* TheoProgress::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  _Internal::HasBits has_bits{};
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // optional string instrument = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          auto str = _internal_mutable_instrument();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          #ifndef NDEBUG
          ::_pbi::VerifyUTF8(str, "HpXVer.TheoProgress.instrument");
          #endif  // !NDEBUG
        } else
          goto handle_unusual;
        continue;
      // optional int32 managed_suffix = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          _Internal::set_has_managed_suffix(&has_bits);
          _impl_.managed_suffix_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // optional string key_suffix = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 26)) {
          auto str = _internal_mutable_key_suffix();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          #ifndef NDEBUG
          ::_pbi::VerifyUTF8(str, "HpXVer.TheoProgress.key_suffix");
          #endif  // !NDEBUG
        } else
          goto handle_unusual;
        continue;
      // optional double value = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 33)) {
          _Internal::set_has_value(&has_bits);
          _impl_.value_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  _impl_._has_bits_.Or(has_bits);
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* TheoProgress::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:HpXVer.TheoProgress)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  // optional string instrument = 1;
  if (cached_has_bits & 0x00000001u) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::VerifyUTF8StringNamedField(
      this->_internal_instrument().data(), static_cast<int>(this->_internal_instrument().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::SERIALIZE,
      "HpXVer.TheoProgress.instrument");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_instrument(), target);
  }

  // optional int32 managed_suffix = 2;
  if (cached_has_bits & 0x00000008u) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(2, this->_internal_managed_suffix(), target);
  }

  // optional string key_suffix = 3;
  if (cached_has_bits & 0x00000002u) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::VerifyUTF8StringNamedField(
      this->_internal_key_suffix().data(), static_cast<int>(this->_internal_key_suffix().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::SERIALIZE,
      "HpXVer.TheoProgress.key_suffix");
    target = stream->WriteStringMaybeAliased(
        3, this->_internal_key_suffix(), target);
  }

  // optional double value = 4;
  if (cached_has_bits & 0x00000004u) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteDoubleToArray(4, this->_internal_value(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:HpXVer.TheoProgress)
  return target;
}

size_t TheoProgress::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:HpXVer.TheoProgress)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x0000000fu) {
    // optional string instrument = 1;
    if (cached_has_bits & 0x00000001u) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
          this->_internal_instrument());
    }

    // optional string key_suffix = 3;
    if (cached_has_bits & 0x00000002u) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
          this->_internal_key_suffix());
    }

    // optional double value = 4;
    if (cached_has_bits & 0x00000004u) {
      total_size += 1 + 8;
    }

    // optional int32 managed_suffix = 2;
    if (cached_has_bits & 0x00000008u) {
      total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_managed_suffix());
    }

  }
  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData TheoProgress::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    TheoProgress::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*TheoProgress::GetClassData() const { return &_class_data_; }


void TheoProgress::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<TheoProgress*>(&to_msg);
  auto& from = static_cast<const TheoProgress&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:HpXVer.TheoProgress)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x0000000fu) {
    if (cached_has_bits & 0x00000001u) {
      _this->_internal_set_instrument(from._internal_instrument());
    }
    if (cached_has_bits & 0x00000002u) {
      _this->_internal_set_key_suffix(from._internal_key_suffix());
    }
    if (cached_has_bits & 0x00000004u) {
      _this->_impl_.value_ = from._impl_.value_;
    }
    if (cached_has_bits & 0x00000008u) {
      _this->_impl_.managed_suffix_ = from._impl_.managed_suffix_;
    }
    _this->_impl_._has_bits_[0] |= cached_has_bits;
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void TheoProgress::CopyFrom(const TheoProgress& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:HpXVer.TheoProgress)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool TheoProgress::IsInitialized() const {
  return true;
}

void TheoProgress::InternalSwap(TheoProgress* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.instrument_, lhs_arena,
      &other->_impl_.instrument_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.key_suffix_, lhs_arena,
      &other->_impl_.key_suffix_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(TheoProgress, _impl_.managed_suffix_)
      + sizeof(TheoProgress::_impl_.managed_suffix_)
      - PROTOBUF_FIELD_OFFSET(TheoProgress, _impl_.value_)>(
          reinterpret_cast<char*>(&_impl_.value_),
          reinterpret_cast<char*>(&other->_impl_.value_));
}

::PROTOBUF_NAMESPACE_ID::Metadata TheoProgress::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_hpx_2eproto_getter, &descriptor_table_hpx_2eproto_once,
      file_level_metadata_hpx_2eproto[3]);
}

// ===================================================================

class HpxPriceProto::_Internal {
 public:
};

HpxPriceProto::HpxPriceProto(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:HpXVer.HpxPriceProto)
}
HpxPriceProto::HpxPriceProto(const HpxPriceProto& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  HpxPriceProto* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.items_){from._impl_.items_}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:HpXVer.HpxPriceProto)
}

inline void HpxPriceProto::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.items_){arena}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

HpxPriceProto::~HpxPriceProto() {
  // @@protoc_insertion_point(destructor:HpXVer.HpxPriceProto)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void HpxPriceProto::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.items_.~RepeatedPtrField();
}

void HpxPriceProto::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void HpxPriceProto::Clear() {
// @@protoc_insertion_point(message_clear_start:HpXVer.HpxPriceProto)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.items_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* HpxPriceProto::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // repeated .HpXVer.PriceInfo items = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_items(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<10>(ptr));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* HpxPriceProto::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:HpXVer.HpxPriceProto)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated .HpXVer.PriceInfo items = 1;
  for (unsigned i = 0,
      n = static_cast<unsigned>(this->_internal_items_size()); i < n; i++) {
    const auto& repfield = this->_internal_items(i);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
        InternalWriteMessage(1, repfield, repfield.GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:HpXVer.HpxPriceProto)
  return target;
}

size_t HpxPriceProto::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:HpXVer.HpxPriceProto)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .HpXVer.PriceInfo items = 1;
  total_size += 1UL * this->_internal_items_size();
  for (const auto& msg : this->_impl_.items_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData HpxPriceProto::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    HpxPriceProto::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*HpxPriceProto::GetClassData() const { return &_class_data_; }


void HpxPriceProto::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<HpxPriceProto*>(&to_msg);
  auto& from = static_cast<const HpxPriceProto&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:HpXVer.HpxPriceProto)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_impl_.items_.MergeFrom(from._impl_.items_);
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void HpxPriceProto::CopyFrom(const HpxPriceProto& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:HpXVer.HpxPriceProto)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool HpxPriceProto::IsInitialized() const {
  return true;
}

void HpxPriceProto::InternalSwap(HpxPriceProto* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.items_.InternalSwap(&other->_impl_.items_);
}

::PROTOBUF_NAMESPACE_ID::Metadata HpxPriceProto::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_hpx_2eproto_getter, &descriptor_table_hpx_2eproto_once,
      file_level_metadata_hpx_2eproto[4]);
}

// ===================================================================

class HpxTheoProgressProto::_Internal {
 public:
};

HpxTheoProgressProto::HpxTheoProgressProto(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:HpXVer.HpxTheoProgressProto)
}
HpxTheoProgressProto::HpxTheoProgressProto(const HpxTheoProgressProto& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  HpxTheoProgressProto* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.items_){from._impl_.items_}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:HpXVer.HpxTheoProgressProto)
}

inline void HpxTheoProgressProto::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.items_){arena}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

HpxTheoProgressProto::~HpxTheoProgressProto() {
  // @@protoc_insertion_point(destructor:HpXVer.HpxTheoProgressProto)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void HpxTheoProgressProto::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.items_.~RepeatedPtrField();
}

void HpxTheoProgressProto::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void HpxTheoProgressProto::Clear() {
// @@protoc_insertion_point(message_clear_start:HpXVer.HpxTheoProgressProto)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.items_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* HpxTheoProgressProto::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // repeated .HpXVer.TheoProgress items = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_items(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<10>(ptr));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* HpxTheoProgressProto::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:HpXVer.HpxTheoProgressProto)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated .HpXVer.TheoProgress items = 1;
  for (unsigned i = 0,
      n = static_cast<unsigned>(this->_internal_items_size()); i < n; i++) {
    const auto& repfield = this->_internal_items(i);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
        InternalWriteMessage(1, repfield, repfield.GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:HpXVer.HpxTheoProgressProto)
  return target;
}

size_t HpxTheoProgressProto::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:HpXVer.HpxTheoProgressProto)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .HpXVer.TheoProgress items = 1;
  total_size += 1UL * this->_internal_items_size();
  for (const auto& msg : this->_impl_.items_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData HpxTheoProgressProto::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    HpxTheoProgressProto::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*HpxTheoProgressProto::GetClassData() const { return &_class_data_; }


void HpxTheoProgressProto::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<HpxTheoProgressProto*>(&to_msg);
  auto& from = static_cast<const HpxTheoProgressProto&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:HpXVer.HpxTheoProgressProto)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_impl_.items_.MergeFrom(from._impl_.items_);
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void HpxTheoProgressProto::CopyFrom(const HpxTheoProgressProto& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:HpXVer.HpxTheoProgressProto)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool HpxTheoProgressProto::IsInitialized() const {
  return true;
}

void HpxTheoProgressProto::InternalSwap(HpxTheoProgressProto* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.items_.InternalSwap(&other->_impl_.items_);
}

::PROTOBUF_NAMESPACE_ID::Metadata HpxTheoProgressProto::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_hpx_2eproto_getter, &descriptor_table_hpx_2eproto_once,
      file_level_metadata_hpx_2eproto[5]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace HpXVer
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::HpXVer::PendingItem*
Arena::CreateMaybeMessage< ::HpXVer::PendingItem >(Arena* arena) {
  return Arena::CreateMessageInternal< ::HpXVer::PendingItem >(arena);
}
template<> PROTOBUF_NOINLINE ::HpXVer::PriceInfo*
Arena::CreateMaybeMessage< ::HpXVer::PriceInfo >(Arena* arena) {
  return Arena::CreateMessageInternal< ::HpXVer::PriceInfo >(arena);
}
template<> PROTOBUF_NOINLINE ::HpXVer::HpxSubProto*
Arena::CreateMaybeMessage< ::HpXVer::HpxSubProto >(Arena* arena) {
  return Arena::CreateMessageInternal< ::HpXVer::HpxSubProto >(arena);
}
template<> PROTOBUF_NOINLINE ::HpXVer::TheoProgress*
Arena::CreateMaybeMessage< ::HpXVer::TheoProgress >(Arena* arena) {
  return Arena::CreateMessageInternal< ::HpXVer::TheoProgress >(arena);
}
template<> PROTOBUF_NOINLINE ::HpXVer::HpxPriceProto*
Arena::CreateMaybeMessage< ::HpXVer::HpxPriceProto >(Arena* arena) {
  return Arena::CreateMessageInternal< ::HpXVer::HpxPriceProto >(arena);
}
template<> PROTOBUF_NOINLINE ::HpXVer::HpxTheoProgressProto*
Arena::CreateMaybeMessage< ::HpXVer::HpxTheoProgressProto >(Arena* arena) {
  return Arena::CreateMessageInternal< ::HpXVer::HpxTheoProgressProto >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
