// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: hpx.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_hpx_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_hpx_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_hpx_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_hpx_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_hpx_2eproto;
namespace HpXVer {
class HpxPriceProto;
struct HpxPriceProtoDefaultTypeInternal;
extern HpxPriceProtoDefaultTypeInternal _HpxPriceProto_default_instance_;
class HpxSubProto;
struct HpxSubProtoDefaultTypeInternal;
extern HpxSubProtoDefaultTypeInternal _HpxSubProto_default_instance_;
class HpxTheoProgressProto;
struct HpxTheoProgressProtoDefaultTypeInternal;
extern HpxTheoProgressProtoDefaultTypeInternal _HpxTheoProgressProto_default_instance_;
class PendingItem;
struct PendingItemDefaultTypeInternal;
extern PendingItemDefaultTypeInternal _PendingItem_default_instance_;
class PriceInfo;
struct PriceInfoDefaultTypeInternal;
extern PriceInfoDefaultTypeInternal _PriceInfo_default_instance_;
class TheoProgress;
struct TheoProgressDefaultTypeInternal;
extern TheoProgressDefaultTypeInternal _TheoProgress_default_instance_;
}  // namespace HpXVer
PROTOBUF_NAMESPACE_OPEN
template<> ::HpXVer::HpxPriceProto* Arena::CreateMaybeMessage<::HpXVer::HpxPriceProto>(Arena*);
template<> ::HpXVer::HpxSubProto* Arena::CreateMaybeMessage<::HpXVer::HpxSubProto>(Arena*);
template<> ::HpXVer::HpxTheoProgressProto* Arena::CreateMaybeMessage<::HpXVer::HpxTheoProgressProto>(Arena*);
template<> ::HpXVer::PendingItem* Arena::CreateMaybeMessage<::HpXVer::PendingItem>(Arena*);
template<> ::HpXVer::PriceInfo* Arena::CreateMaybeMessage<::HpXVer::PriceInfo>(Arena*);
template<> ::HpXVer::TheoProgress* Arena::CreateMaybeMessage<::HpXVer::TheoProgress>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace HpXVer {

// ===================================================================

class PendingItem final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:HpXVer.PendingItem) */ {
 public:
  inline PendingItem() : PendingItem(nullptr) {}
  ~PendingItem() override;
  explicit PROTOBUF_CONSTEXPR PendingItem(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  PendingItem(const PendingItem& from);
  PendingItem(PendingItem&& from) noexcept
    : PendingItem() {
    *this = ::std::move(from);
  }

  inline PendingItem& operator=(const PendingItem& from) {
    CopyFrom(from);
    return *this;
  }
  inline PendingItem& operator=(PendingItem&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const PendingItem& default_instance() {
    return *internal_default_instance();
  }
  static inline const PendingItem* internal_default_instance() {
    return reinterpret_cast<const PendingItem*>(
               &_PendingItem_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(PendingItem& a, PendingItem& b) {
    a.Swap(&b);
  }
  inline void Swap(PendingItem* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(PendingItem* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  PendingItem* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<PendingItem>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const PendingItem& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const PendingItem& from) {
    PendingItem::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(PendingItem* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "HpXVer.PendingItem";
  }
  protected:
  explicit PendingItem(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kPriceFieldNumber = 1,
    kVolumeFieldNumber = 2,
  };
  // optional double price = 1;
  bool has_price() const;
  private:
  bool _internal_has_price() const;
  public:
  void clear_price();
  double price() const;
  void set_price(double value);
  private:
  double _internal_price() const;
  void _internal_set_price(double value);
  public:

  // optional int32 volume = 2;
  bool has_volume() const;
  private:
  bool _internal_has_volume() const;
  public:
  void clear_volume();
  int32_t volume() const;
  void set_volume(int32_t value);
  private:
  int32_t _internal_volume() const;
  void _internal_set_volume(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:HpXVer.PendingItem)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
    double price_;
    int32_t volume_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_hpx_2eproto;
};
// -------------------------------------------------------------------

class PriceInfo final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:HpXVer.PriceInfo) */ {
 public:
  inline PriceInfo() : PriceInfo(nullptr) {}
  ~PriceInfo() override;
  explicit PROTOBUF_CONSTEXPR PriceInfo(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  PriceInfo(const PriceInfo& from);
  PriceInfo(PriceInfo&& from) noexcept
    : PriceInfo() {
    *this = ::std::move(from);
  }

  inline PriceInfo& operator=(const PriceInfo& from) {
    CopyFrom(from);
    return *this;
  }
  inline PriceInfo& operator=(PriceInfo&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const PriceInfo& default_instance() {
    return *internal_default_instance();
  }
  static inline const PriceInfo* internal_default_instance() {
    return reinterpret_cast<const PriceInfo*>(
               &_PriceInfo_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(PriceInfo& a, PriceInfo& b) {
    a.Swap(&b);
  }
  inline void Swap(PriceInfo* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(PriceInfo* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  PriceInfo* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<PriceInfo>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const PriceInfo& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const PriceInfo& from) {
    PriceInfo::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(PriceInfo* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "HpXVer.PriceInfo";
  }
  protected:
  explicit PriceInfo(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kPendingBuyVolumeDictFieldNumber = 4,
    kPendingSellVolumeDictFieldNumber = 5,
    kInstrumentFieldNumber = 1,
    kForceWithdrawBuyPriceFieldNumber = 2,
    kForceWithdrawSellPriceFieldNumber = 3,
  };
  // repeated .HpXVer.PendingItem pending_buy_volume_dict = 4;
  int pending_buy_volume_dict_size() const;
  private:
  int _internal_pending_buy_volume_dict_size() const;
  public:
  void clear_pending_buy_volume_dict();
  ::HpXVer::PendingItem* mutable_pending_buy_volume_dict(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::HpXVer::PendingItem >*
      mutable_pending_buy_volume_dict();
  private:
  const ::HpXVer::PendingItem& _internal_pending_buy_volume_dict(int index) const;
  ::HpXVer::PendingItem* _internal_add_pending_buy_volume_dict();
  public:
  const ::HpXVer::PendingItem& pending_buy_volume_dict(int index) const;
  ::HpXVer::PendingItem* add_pending_buy_volume_dict();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::HpXVer::PendingItem >&
      pending_buy_volume_dict() const;

  // repeated .HpXVer.PendingItem pending_sell_volume_dict = 5;
  int pending_sell_volume_dict_size() const;
  private:
  int _internal_pending_sell_volume_dict_size() const;
  public:
  void clear_pending_sell_volume_dict();
  ::HpXVer::PendingItem* mutable_pending_sell_volume_dict(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::HpXVer::PendingItem >*
      mutable_pending_sell_volume_dict();
  private:
  const ::HpXVer::PendingItem& _internal_pending_sell_volume_dict(int index) const;
  ::HpXVer::PendingItem* _internal_add_pending_sell_volume_dict();
  public:
  const ::HpXVer::PendingItem& pending_sell_volume_dict(int index) const;
  ::HpXVer::PendingItem* add_pending_sell_volume_dict();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::HpXVer::PendingItem >&
      pending_sell_volume_dict() const;

  // optional string instrument = 1;
  bool has_instrument() const;
  private:
  bool _internal_has_instrument() const;
  public:
  void clear_instrument();
  const std::string& instrument() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_instrument(ArgT0&& arg0, ArgT... args);
  std::string* mutable_instrument();
  PROTOBUF_NODISCARD std::string* release_instrument();
  void set_allocated_instrument(std::string* instrument);
  private:
  const std::string& _internal_instrument() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_instrument(const std::string& value);
  std::string* _internal_mutable_instrument();
  public:

  // optional double force_withdraw_buy_price = 2;
  bool has_force_withdraw_buy_price() const;
  private:
  bool _internal_has_force_withdraw_buy_price() const;
  public:
  void clear_force_withdraw_buy_price();
  double force_withdraw_buy_price() const;
  void set_force_withdraw_buy_price(double value);
  private:
  double _internal_force_withdraw_buy_price() const;
  void _internal_set_force_withdraw_buy_price(double value);
  public:

  // optional double force_withdraw_sell_price = 3;
  bool has_force_withdraw_sell_price() const;
  private:
  bool _internal_has_force_withdraw_sell_price() const;
  public:
  void clear_force_withdraw_sell_price();
  double force_withdraw_sell_price() const;
  void set_force_withdraw_sell_price(double value);
  private:
  double _internal_force_withdraw_sell_price() const;
  void _internal_set_force_withdraw_sell_price(double value);
  public:

  // @@protoc_insertion_point(class_scope:HpXVer.PriceInfo)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::HpXVer::PendingItem > pending_buy_volume_dict_;
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::HpXVer::PendingItem > pending_sell_volume_dict_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr instrument_;
    double force_withdraw_buy_price_;
    double force_withdraw_sell_price_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_hpx_2eproto;
};
// -------------------------------------------------------------------

class HpxSubProto final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:HpXVer.HpxSubProto) */ {
 public:
  inline HpxSubProto() : HpxSubProto(nullptr) {}
  ~HpxSubProto() override;
  explicit PROTOBUF_CONSTEXPR HpxSubProto(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  HpxSubProto(const HpxSubProto& from);
  HpxSubProto(HpxSubProto&& from) noexcept
    : HpxSubProto() {
    *this = ::std::move(from);
  }

  inline HpxSubProto& operator=(const HpxSubProto& from) {
    CopyFrom(from);
    return *this;
  }
  inline HpxSubProto& operator=(HpxSubProto&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const HpxSubProto& default_instance() {
    return *internal_default_instance();
  }
  static inline const HpxSubProto* internal_default_instance() {
    return reinterpret_cast<const HpxSubProto*>(
               &_HpxSubProto_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(HpxSubProto& a, HpxSubProto& b) {
    a.Swap(&b);
  }
  inline void Swap(HpxSubProto* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(HpxSubProto* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  HpxSubProto* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<HpxSubProto>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const HpxSubProto& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const HpxSubProto& from) {
    HpxSubProto::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(HpxSubProto* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "HpXVer.HpxSubProto";
  }
  protected:
  explicit HpxSubProto(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kKeySuffixFieldNumber = 2,
    kManagedSuffixFieldNumber = 1,
  };
  // optional string key_suffix = 2;
  bool has_key_suffix() const;
  private:
  bool _internal_has_key_suffix() const;
  public:
  void clear_key_suffix();
  const std::string& key_suffix() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_key_suffix(ArgT0&& arg0, ArgT... args);
  std::string* mutable_key_suffix();
  PROTOBUF_NODISCARD std::string* release_key_suffix();
  void set_allocated_key_suffix(std::string* key_suffix);
  private:
  const std::string& _internal_key_suffix() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_key_suffix(const std::string& value);
  std::string* _internal_mutable_key_suffix();
  public:

  // optional int32 managed_suffix = 1;
  bool has_managed_suffix() const;
  private:
  bool _internal_has_managed_suffix() const;
  public:
  void clear_managed_suffix();
  int32_t managed_suffix() const;
  void set_managed_suffix(int32_t value);
  private:
  int32_t _internal_managed_suffix() const;
  void _internal_set_managed_suffix(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:HpXVer.HpxSubProto)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr key_suffix_;
    int32_t managed_suffix_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_hpx_2eproto;
};
// -------------------------------------------------------------------

class TheoProgress final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:HpXVer.TheoProgress) */ {
 public:
  inline TheoProgress() : TheoProgress(nullptr) {}
  ~TheoProgress() override;
  explicit PROTOBUF_CONSTEXPR TheoProgress(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  TheoProgress(const TheoProgress& from);
  TheoProgress(TheoProgress&& from) noexcept
    : TheoProgress() {
    *this = ::std::move(from);
  }

  inline TheoProgress& operator=(const TheoProgress& from) {
    CopyFrom(from);
    return *this;
  }
  inline TheoProgress& operator=(TheoProgress&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const TheoProgress& default_instance() {
    return *internal_default_instance();
  }
  static inline const TheoProgress* internal_default_instance() {
    return reinterpret_cast<const TheoProgress*>(
               &_TheoProgress_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(TheoProgress& a, TheoProgress& b) {
    a.Swap(&b);
  }
  inline void Swap(TheoProgress* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(TheoProgress* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  TheoProgress* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<TheoProgress>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const TheoProgress& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const TheoProgress& from) {
    TheoProgress::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(TheoProgress* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "HpXVer.TheoProgress";
  }
  protected:
  explicit TheoProgress(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kInstrumentFieldNumber = 1,
    kKeySuffixFieldNumber = 3,
    kValueFieldNumber = 4,
    kManagedSuffixFieldNumber = 2,
  };
  // optional string instrument = 1;
  bool has_instrument() const;
  private:
  bool _internal_has_instrument() const;
  public:
  void clear_instrument();
  const std::string& instrument() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_instrument(ArgT0&& arg0, ArgT... args);
  std::string* mutable_instrument();
  PROTOBUF_NODISCARD std::string* release_instrument();
  void set_allocated_instrument(std::string* instrument);
  private:
  const std::string& _internal_instrument() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_instrument(const std::string& value);
  std::string* _internal_mutable_instrument();
  public:

  // optional string key_suffix = 3;
  bool has_key_suffix() const;
  private:
  bool _internal_has_key_suffix() const;
  public:
  void clear_key_suffix();
  const std::string& key_suffix() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_key_suffix(ArgT0&& arg0, ArgT... args);
  std::string* mutable_key_suffix();
  PROTOBUF_NODISCARD std::string* release_key_suffix();
  void set_allocated_key_suffix(std::string* key_suffix);
  private:
  const std::string& _internal_key_suffix() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_key_suffix(const std::string& value);
  std::string* _internal_mutable_key_suffix();
  public:

  // optional double value = 4;
  bool has_value() const;
  private:
  bool _internal_has_value() const;
  public:
  void clear_value();
  double value() const;
  void set_value(double value);
  private:
  double _internal_value() const;
  void _internal_set_value(double value);
  public:

  // optional int32 managed_suffix = 2;
  bool has_managed_suffix() const;
  private:
  bool _internal_has_managed_suffix() const;
  public:
  void clear_managed_suffix();
  int32_t managed_suffix() const;
  void set_managed_suffix(int32_t value);
  private:
  int32_t _internal_managed_suffix() const;
  void _internal_set_managed_suffix(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:HpXVer.TheoProgress)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr instrument_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr key_suffix_;
    double value_;
    int32_t managed_suffix_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_hpx_2eproto;
};
// -------------------------------------------------------------------

class HpxPriceProto final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:HpXVer.HpxPriceProto) */ {
 public:
  inline HpxPriceProto() : HpxPriceProto(nullptr) {}
  ~HpxPriceProto() override;
  explicit PROTOBUF_CONSTEXPR HpxPriceProto(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  HpxPriceProto(const HpxPriceProto& from);
  HpxPriceProto(HpxPriceProto&& from) noexcept
    : HpxPriceProto() {
    *this = ::std::move(from);
  }

  inline HpxPriceProto& operator=(const HpxPriceProto& from) {
    CopyFrom(from);
    return *this;
  }
  inline HpxPriceProto& operator=(HpxPriceProto&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const HpxPriceProto& default_instance() {
    return *internal_default_instance();
  }
  static inline const HpxPriceProto* internal_default_instance() {
    return reinterpret_cast<const HpxPriceProto*>(
               &_HpxPriceProto_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    4;

  friend void swap(HpxPriceProto& a, HpxPriceProto& b) {
    a.Swap(&b);
  }
  inline void Swap(HpxPriceProto* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(HpxPriceProto* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  HpxPriceProto* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<HpxPriceProto>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const HpxPriceProto& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const HpxPriceProto& from) {
    HpxPriceProto::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(HpxPriceProto* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "HpXVer.HpxPriceProto";
  }
  protected:
  explicit HpxPriceProto(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kItemsFieldNumber = 1,
  };
  // repeated .HpXVer.PriceInfo items = 1;
  int items_size() const;
  private:
  int _internal_items_size() const;
  public:
  void clear_items();
  ::HpXVer::PriceInfo* mutable_items(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::HpXVer::PriceInfo >*
      mutable_items();
  private:
  const ::HpXVer::PriceInfo& _internal_items(int index) const;
  ::HpXVer::PriceInfo* _internal_add_items();
  public:
  const ::HpXVer::PriceInfo& items(int index) const;
  ::HpXVer::PriceInfo* add_items();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::HpXVer::PriceInfo >&
      items() const;

  // @@protoc_insertion_point(class_scope:HpXVer.HpxPriceProto)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::HpXVer::PriceInfo > items_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_hpx_2eproto;
};
// -------------------------------------------------------------------

class HpxTheoProgressProto final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:HpXVer.HpxTheoProgressProto) */ {
 public:
  inline HpxTheoProgressProto() : HpxTheoProgressProto(nullptr) {}
  ~HpxTheoProgressProto() override;
  explicit PROTOBUF_CONSTEXPR HpxTheoProgressProto(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  HpxTheoProgressProto(const HpxTheoProgressProto& from);
  HpxTheoProgressProto(HpxTheoProgressProto&& from) noexcept
    : HpxTheoProgressProto() {
    *this = ::std::move(from);
  }

  inline HpxTheoProgressProto& operator=(const HpxTheoProgressProto& from) {
    CopyFrom(from);
    return *this;
  }
  inline HpxTheoProgressProto& operator=(HpxTheoProgressProto&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const HpxTheoProgressProto& default_instance() {
    return *internal_default_instance();
  }
  static inline const HpxTheoProgressProto* internal_default_instance() {
    return reinterpret_cast<const HpxTheoProgressProto*>(
               &_HpxTheoProgressProto_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    5;

  friend void swap(HpxTheoProgressProto& a, HpxTheoProgressProto& b) {
    a.Swap(&b);
  }
  inline void Swap(HpxTheoProgressProto* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(HpxTheoProgressProto* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  HpxTheoProgressProto* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<HpxTheoProgressProto>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const HpxTheoProgressProto& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const HpxTheoProgressProto& from) {
    HpxTheoProgressProto::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(HpxTheoProgressProto* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "HpXVer.HpxTheoProgressProto";
  }
  protected:
  explicit HpxTheoProgressProto(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kItemsFieldNumber = 1,
  };
  // repeated .HpXVer.TheoProgress items = 1;
  int items_size() const;
  private:
  int _internal_items_size() const;
  public:
  void clear_items();
  ::HpXVer::TheoProgress* mutable_items(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::HpXVer::TheoProgress >*
      mutable_items();
  private:
  const ::HpXVer::TheoProgress& _internal_items(int index) const;
  ::HpXVer::TheoProgress* _internal_add_items();
  public:
  const ::HpXVer::TheoProgress& items(int index) const;
  ::HpXVer::TheoProgress* add_items();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::HpXVer::TheoProgress >&
      items() const;

  // @@protoc_insertion_point(class_scope:HpXVer.HpxTheoProgressProto)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::HpXVer::TheoProgress > items_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_hpx_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// PendingItem

// optional double price = 1;
inline bool PendingItem::_internal_has_price() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool PendingItem::has_price() const {
  return _internal_has_price();
}
inline void PendingItem::clear_price() {
  _impl_.price_ = 0;
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline double PendingItem::_internal_price() const {
  return _impl_.price_;
}
inline double PendingItem::price() const {
  // @@protoc_insertion_point(field_get:HpXVer.PendingItem.price)
  return _internal_price();
}
inline void PendingItem::_internal_set_price(double value) {
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.price_ = value;
}
inline void PendingItem::set_price(double value) {
  _internal_set_price(value);
  // @@protoc_insertion_point(field_set:HpXVer.PendingItem.price)
}

// optional int32 volume = 2;
inline bool PendingItem::_internal_has_volume() const {
  bool value = (_impl_._has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline bool PendingItem::has_volume() const {
  return _internal_has_volume();
}
inline void PendingItem::clear_volume() {
  _impl_.volume_ = 0;
  _impl_._has_bits_[0] &= ~0x00000002u;
}
inline int32_t PendingItem::_internal_volume() const {
  return _impl_.volume_;
}
inline int32_t PendingItem::volume() const {
  // @@protoc_insertion_point(field_get:HpXVer.PendingItem.volume)
  return _internal_volume();
}
inline void PendingItem::_internal_set_volume(int32_t value) {
  _impl_._has_bits_[0] |= 0x00000002u;
  _impl_.volume_ = value;
}
inline void PendingItem::set_volume(int32_t value) {
  _internal_set_volume(value);
  // @@protoc_insertion_point(field_set:HpXVer.PendingItem.volume)
}

// -------------------------------------------------------------------

// PriceInfo

// optional string instrument = 1;
inline bool PriceInfo::_internal_has_instrument() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool PriceInfo::has_instrument() const {
  return _internal_has_instrument();
}
inline void PriceInfo::clear_instrument() {
  _impl_.instrument_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline const std::string& PriceInfo::instrument() const {
  // @@protoc_insertion_point(field_get:HpXVer.PriceInfo.instrument)
  return _internal_instrument();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void PriceInfo::set_instrument(ArgT0&& arg0, ArgT... args) {
 _impl_._has_bits_[0] |= 0x00000001u;
 _impl_.instrument_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:HpXVer.PriceInfo.instrument)
}
inline std::string* PriceInfo::mutable_instrument() {
  std::string* _s = _internal_mutable_instrument();
  // @@protoc_insertion_point(field_mutable:HpXVer.PriceInfo.instrument)
  return _s;
}
inline const std::string& PriceInfo::_internal_instrument() const {
  return _impl_.instrument_.Get();
}
inline void PriceInfo::_internal_set_instrument(const std::string& value) {
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.instrument_.Set(value, GetArenaForAllocation());
}
inline std::string* PriceInfo::_internal_mutable_instrument() {
  _impl_._has_bits_[0] |= 0x00000001u;
  return _impl_.instrument_.Mutable(GetArenaForAllocation());
}
inline std::string* PriceInfo::release_instrument() {
  // @@protoc_insertion_point(field_release:HpXVer.PriceInfo.instrument)
  if (!_internal_has_instrument()) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000001u;
  auto* p = _impl_.instrument_.Release();
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.instrument_.IsDefault()) {
    _impl_.instrument_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  return p;
}
inline void PriceInfo::set_allocated_instrument(std::string* instrument) {
  if (instrument != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  _impl_.instrument_.SetAllocated(instrument, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.instrument_.IsDefault()) {
    _impl_.instrument_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:HpXVer.PriceInfo.instrument)
}

// optional double force_withdraw_buy_price = 2;
inline bool PriceInfo::_internal_has_force_withdraw_buy_price() const {
  bool value = (_impl_._has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline bool PriceInfo::has_force_withdraw_buy_price() const {
  return _internal_has_force_withdraw_buy_price();
}
inline void PriceInfo::clear_force_withdraw_buy_price() {
  _impl_.force_withdraw_buy_price_ = 0;
  _impl_._has_bits_[0] &= ~0x00000002u;
}
inline double PriceInfo::_internal_force_withdraw_buy_price() const {
  return _impl_.force_withdraw_buy_price_;
}
inline double PriceInfo::force_withdraw_buy_price() const {
  // @@protoc_insertion_point(field_get:HpXVer.PriceInfo.force_withdraw_buy_price)
  return _internal_force_withdraw_buy_price();
}
inline void PriceInfo::_internal_set_force_withdraw_buy_price(double value) {
  _impl_._has_bits_[0] |= 0x00000002u;
  _impl_.force_withdraw_buy_price_ = value;
}
inline void PriceInfo::set_force_withdraw_buy_price(double value) {
  _internal_set_force_withdraw_buy_price(value);
  // @@protoc_insertion_point(field_set:HpXVer.PriceInfo.force_withdraw_buy_price)
}

// optional double force_withdraw_sell_price = 3;
inline bool PriceInfo::_internal_has_force_withdraw_sell_price() const {
  bool value = (_impl_._has_bits_[0] & 0x00000004u) != 0;
  return value;
}
inline bool PriceInfo::has_force_withdraw_sell_price() const {
  return _internal_has_force_withdraw_sell_price();
}
inline void PriceInfo::clear_force_withdraw_sell_price() {
  _impl_.force_withdraw_sell_price_ = 0;
  _impl_._has_bits_[0] &= ~0x00000004u;
}
inline double PriceInfo::_internal_force_withdraw_sell_price() const {
  return _impl_.force_withdraw_sell_price_;
}
inline double PriceInfo::force_withdraw_sell_price() const {
  // @@protoc_insertion_point(field_get:HpXVer.PriceInfo.force_withdraw_sell_price)
  return _internal_force_withdraw_sell_price();
}
inline void PriceInfo::_internal_set_force_withdraw_sell_price(double value) {
  _impl_._has_bits_[0] |= 0x00000004u;
  _impl_.force_withdraw_sell_price_ = value;
}
inline void PriceInfo::set_force_withdraw_sell_price(double value) {
  _internal_set_force_withdraw_sell_price(value);
  // @@protoc_insertion_point(field_set:HpXVer.PriceInfo.force_withdraw_sell_price)
}

// repeated .HpXVer.PendingItem pending_buy_volume_dict = 4;
inline int PriceInfo::_internal_pending_buy_volume_dict_size() const {
  return _impl_.pending_buy_volume_dict_.size();
}
inline int PriceInfo::pending_buy_volume_dict_size() const {
  return _internal_pending_buy_volume_dict_size();
}
inline void PriceInfo::clear_pending_buy_volume_dict() {
  _impl_.pending_buy_volume_dict_.Clear();
}
inline ::HpXVer::PendingItem* PriceInfo::mutable_pending_buy_volume_dict(int index) {
  // @@protoc_insertion_point(field_mutable:HpXVer.PriceInfo.pending_buy_volume_dict)
  return _impl_.pending_buy_volume_dict_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::HpXVer::PendingItem >*
PriceInfo::mutable_pending_buy_volume_dict() {
  // @@protoc_insertion_point(field_mutable_list:HpXVer.PriceInfo.pending_buy_volume_dict)
  return &_impl_.pending_buy_volume_dict_;
}
inline const ::HpXVer::PendingItem& PriceInfo::_internal_pending_buy_volume_dict(int index) const {
  return _impl_.pending_buy_volume_dict_.Get(index);
}
inline const ::HpXVer::PendingItem& PriceInfo::pending_buy_volume_dict(int index) const {
  // @@protoc_insertion_point(field_get:HpXVer.PriceInfo.pending_buy_volume_dict)
  return _internal_pending_buy_volume_dict(index);
}
inline ::HpXVer::PendingItem* PriceInfo::_internal_add_pending_buy_volume_dict() {
  return _impl_.pending_buy_volume_dict_.Add();
}
inline ::HpXVer::PendingItem* PriceInfo::add_pending_buy_volume_dict() {
  ::HpXVer::PendingItem* _add = _internal_add_pending_buy_volume_dict();
  // @@protoc_insertion_point(field_add:HpXVer.PriceInfo.pending_buy_volume_dict)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::HpXVer::PendingItem >&
PriceInfo::pending_buy_volume_dict() const {
  // @@protoc_insertion_point(field_list:HpXVer.PriceInfo.pending_buy_volume_dict)
  return _impl_.pending_buy_volume_dict_;
}

// repeated .HpXVer.PendingItem pending_sell_volume_dict = 5;
inline int PriceInfo::_internal_pending_sell_volume_dict_size() const {
  return _impl_.pending_sell_volume_dict_.size();
}
inline int PriceInfo::pending_sell_volume_dict_size() const {
  return _internal_pending_sell_volume_dict_size();
}
inline void PriceInfo::clear_pending_sell_volume_dict() {
  _impl_.pending_sell_volume_dict_.Clear();
}
inline ::HpXVer::PendingItem* PriceInfo::mutable_pending_sell_volume_dict(int index) {
  // @@protoc_insertion_point(field_mutable:HpXVer.PriceInfo.pending_sell_volume_dict)
  return _impl_.pending_sell_volume_dict_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::HpXVer::PendingItem >*
PriceInfo::mutable_pending_sell_volume_dict() {
  // @@protoc_insertion_point(field_mutable_list:HpXVer.PriceInfo.pending_sell_volume_dict)
  return &_impl_.pending_sell_volume_dict_;
}
inline const ::HpXVer::PendingItem& PriceInfo::_internal_pending_sell_volume_dict(int index) const {
  return _impl_.pending_sell_volume_dict_.Get(index);
}
inline const ::HpXVer::PendingItem& PriceInfo::pending_sell_volume_dict(int index) const {
  // @@protoc_insertion_point(field_get:HpXVer.PriceInfo.pending_sell_volume_dict)
  return _internal_pending_sell_volume_dict(index);
}
inline ::HpXVer::PendingItem* PriceInfo::_internal_add_pending_sell_volume_dict() {
  return _impl_.pending_sell_volume_dict_.Add();
}
inline ::HpXVer::PendingItem* PriceInfo::add_pending_sell_volume_dict() {
  ::HpXVer::PendingItem* _add = _internal_add_pending_sell_volume_dict();
  // @@protoc_insertion_point(field_add:HpXVer.PriceInfo.pending_sell_volume_dict)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::HpXVer::PendingItem >&
PriceInfo::pending_sell_volume_dict() const {
  // @@protoc_insertion_point(field_list:HpXVer.PriceInfo.pending_sell_volume_dict)
  return _impl_.pending_sell_volume_dict_;
}

// -------------------------------------------------------------------

// HpxSubProto

// optional int32 managed_suffix = 1;
inline bool HpxSubProto::_internal_has_managed_suffix() const {
  bool value = (_impl_._has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline bool HpxSubProto::has_managed_suffix() const {
  return _internal_has_managed_suffix();
}
inline void HpxSubProto::clear_managed_suffix() {
  _impl_.managed_suffix_ = 0;
  _impl_._has_bits_[0] &= ~0x00000002u;
}
inline int32_t HpxSubProto::_internal_managed_suffix() const {
  return _impl_.managed_suffix_;
}
inline int32_t HpxSubProto::managed_suffix() const {
  // @@protoc_insertion_point(field_get:HpXVer.HpxSubProto.managed_suffix)
  return _internal_managed_suffix();
}
inline void HpxSubProto::_internal_set_managed_suffix(int32_t value) {
  _impl_._has_bits_[0] |= 0x00000002u;
  _impl_.managed_suffix_ = value;
}
inline void HpxSubProto::set_managed_suffix(int32_t value) {
  _internal_set_managed_suffix(value);
  // @@protoc_insertion_point(field_set:HpXVer.HpxSubProto.managed_suffix)
}

// optional string key_suffix = 2;
inline bool HpxSubProto::_internal_has_key_suffix() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool HpxSubProto::has_key_suffix() const {
  return _internal_has_key_suffix();
}
inline void HpxSubProto::clear_key_suffix() {
  _impl_.key_suffix_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline const std::string& HpxSubProto::key_suffix() const {
  // @@protoc_insertion_point(field_get:HpXVer.HpxSubProto.key_suffix)
  return _internal_key_suffix();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void HpxSubProto::set_key_suffix(ArgT0&& arg0, ArgT... args) {
 _impl_._has_bits_[0] |= 0x00000001u;
 _impl_.key_suffix_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:HpXVer.HpxSubProto.key_suffix)
}
inline std::string* HpxSubProto::mutable_key_suffix() {
  std::string* _s = _internal_mutable_key_suffix();
  // @@protoc_insertion_point(field_mutable:HpXVer.HpxSubProto.key_suffix)
  return _s;
}
inline const std::string& HpxSubProto::_internal_key_suffix() const {
  return _impl_.key_suffix_.Get();
}
inline void HpxSubProto::_internal_set_key_suffix(const std::string& value) {
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.key_suffix_.Set(value, GetArenaForAllocation());
}
inline std::string* HpxSubProto::_internal_mutable_key_suffix() {
  _impl_._has_bits_[0] |= 0x00000001u;
  return _impl_.key_suffix_.Mutable(GetArenaForAllocation());
}
inline std::string* HpxSubProto::release_key_suffix() {
  // @@protoc_insertion_point(field_release:HpXVer.HpxSubProto.key_suffix)
  if (!_internal_has_key_suffix()) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000001u;
  auto* p = _impl_.key_suffix_.Release();
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.key_suffix_.IsDefault()) {
    _impl_.key_suffix_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  return p;
}
inline void HpxSubProto::set_allocated_key_suffix(std::string* key_suffix) {
  if (key_suffix != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  _impl_.key_suffix_.SetAllocated(key_suffix, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.key_suffix_.IsDefault()) {
    _impl_.key_suffix_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:HpXVer.HpxSubProto.key_suffix)
}

// -------------------------------------------------------------------

// TheoProgress

// optional string instrument = 1;
inline bool TheoProgress::_internal_has_instrument() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool TheoProgress::has_instrument() const {
  return _internal_has_instrument();
}
inline void TheoProgress::clear_instrument() {
  _impl_.instrument_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline const std::string& TheoProgress::instrument() const {
  // @@protoc_insertion_point(field_get:HpXVer.TheoProgress.instrument)
  return _internal_instrument();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void TheoProgress::set_instrument(ArgT0&& arg0, ArgT... args) {
 _impl_._has_bits_[0] |= 0x00000001u;
 _impl_.instrument_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:HpXVer.TheoProgress.instrument)
}
inline std::string* TheoProgress::mutable_instrument() {
  std::string* _s = _internal_mutable_instrument();
  // @@protoc_insertion_point(field_mutable:HpXVer.TheoProgress.instrument)
  return _s;
}
inline const std::string& TheoProgress::_internal_instrument() const {
  return _impl_.instrument_.Get();
}
inline void TheoProgress::_internal_set_instrument(const std::string& value) {
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.instrument_.Set(value, GetArenaForAllocation());
}
inline std::string* TheoProgress::_internal_mutable_instrument() {
  _impl_._has_bits_[0] |= 0x00000001u;
  return _impl_.instrument_.Mutable(GetArenaForAllocation());
}
inline std::string* TheoProgress::release_instrument() {
  // @@protoc_insertion_point(field_release:HpXVer.TheoProgress.instrument)
  if (!_internal_has_instrument()) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000001u;
  auto* p = _impl_.instrument_.Release();
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.instrument_.IsDefault()) {
    _impl_.instrument_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  return p;
}
inline void TheoProgress::set_allocated_instrument(std::string* instrument) {
  if (instrument != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  _impl_.instrument_.SetAllocated(instrument, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.instrument_.IsDefault()) {
    _impl_.instrument_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:HpXVer.TheoProgress.instrument)
}

// optional int32 managed_suffix = 2;
inline bool TheoProgress::_internal_has_managed_suffix() const {
  bool value = (_impl_._has_bits_[0] & 0x00000008u) != 0;
  return value;
}
inline bool TheoProgress::has_managed_suffix() const {
  return _internal_has_managed_suffix();
}
inline void TheoProgress::clear_managed_suffix() {
  _impl_.managed_suffix_ = 0;
  _impl_._has_bits_[0] &= ~0x00000008u;
}
inline int32_t TheoProgress::_internal_managed_suffix() const {
  return _impl_.managed_suffix_;
}
inline int32_t TheoProgress::managed_suffix() const {
  // @@protoc_insertion_point(field_get:HpXVer.TheoProgress.managed_suffix)
  return _internal_managed_suffix();
}
inline void TheoProgress::_internal_set_managed_suffix(int32_t value) {
  _impl_._has_bits_[0] |= 0x00000008u;
  _impl_.managed_suffix_ = value;
}
inline void TheoProgress::set_managed_suffix(int32_t value) {
  _internal_set_managed_suffix(value);
  // @@protoc_insertion_point(field_set:HpXVer.TheoProgress.managed_suffix)
}

// optional string key_suffix = 3;
inline bool TheoProgress::_internal_has_key_suffix() const {
  bool value = (_impl_._has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline bool TheoProgress::has_key_suffix() const {
  return _internal_has_key_suffix();
}
inline void TheoProgress::clear_key_suffix() {
  _impl_.key_suffix_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000002u;
}
inline const std::string& TheoProgress::key_suffix() const {
  // @@protoc_insertion_point(field_get:HpXVer.TheoProgress.key_suffix)
  return _internal_key_suffix();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void TheoProgress::set_key_suffix(ArgT0&& arg0, ArgT... args) {
 _impl_._has_bits_[0] |= 0x00000002u;
 _impl_.key_suffix_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:HpXVer.TheoProgress.key_suffix)
}
inline std::string* TheoProgress::mutable_key_suffix() {
  std::string* _s = _internal_mutable_key_suffix();
  // @@protoc_insertion_point(field_mutable:HpXVer.TheoProgress.key_suffix)
  return _s;
}
inline const std::string& TheoProgress::_internal_key_suffix() const {
  return _impl_.key_suffix_.Get();
}
inline void TheoProgress::_internal_set_key_suffix(const std::string& value) {
  _impl_._has_bits_[0] |= 0x00000002u;
  _impl_.key_suffix_.Set(value, GetArenaForAllocation());
}
inline std::string* TheoProgress::_internal_mutable_key_suffix() {
  _impl_._has_bits_[0] |= 0x00000002u;
  return _impl_.key_suffix_.Mutable(GetArenaForAllocation());
}
inline std::string* TheoProgress::release_key_suffix() {
  // @@protoc_insertion_point(field_release:HpXVer.TheoProgress.key_suffix)
  if (!_internal_has_key_suffix()) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000002u;
  auto* p = _impl_.key_suffix_.Release();
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.key_suffix_.IsDefault()) {
    _impl_.key_suffix_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  return p;
}
inline void TheoProgress::set_allocated_key_suffix(std::string* key_suffix) {
  if (key_suffix != nullptr) {
    _impl_._has_bits_[0] |= 0x00000002u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000002u;
  }
  _impl_.key_suffix_.SetAllocated(key_suffix, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.key_suffix_.IsDefault()) {
    _impl_.key_suffix_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:HpXVer.TheoProgress.key_suffix)
}

// optional double value = 4;
inline bool TheoProgress::_internal_has_value() const {
  bool value = (_impl_._has_bits_[0] & 0x00000004u) != 0;
  return value;
}
inline bool TheoProgress::has_value() const {
  return _internal_has_value();
}
inline void TheoProgress::clear_value() {
  _impl_.value_ = 0;
  _impl_._has_bits_[0] &= ~0x00000004u;
}
inline double TheoProgress::_internal_value() const {
  return _impl_.value_;
}
inline double TheoProgress::value() const {
  // @@protoc_insertion_point(field_get:HpXVer.TheoProgress.value)
  return _internal_value();
}
inline void TheoProgress::_internal_set_value(double value) {
  _impl_._has_bits_[0] |= 0x00000004u;
  _impl_.value_ = value;
}
inline void TheoProgress::set_value(double value) {
  _internal_set_value(value);
  // @@protoc_insertion_point(field_set:HpXVer.TheoProgress.value)
}

// -------------------------------------------------------------------

// HpxPriceProto

// repeated .HpXVer.PriceInfo items = 1;
inline int HpxPriceProto::_internal_items_size() const {
  return _impl_.items_.size();
}
inline int HpxPriceProto::items_size() const {
  return _internal_items_size();
}
inline void HpxPriceProto::clear_items() {
  _impl_.items_.Clear();
}
inline ::HpXVer::PriceInfo* HpxPriceProto::mutable_items(int index) {
  // @@protoc_insertion_point(field_mutable:HpXVer.HpxPriceProto.items)
  return _impl_.items_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::HpXVer::PriceInfo >*
HpxPriceProto::mutable_items() {
  // @@protoc_insertion_point(field_mutable_list:HpXVer.HpxPriceProto.items)
  return &_impl_.items_;
}
inline const ::HpXVer::PriceInfo& HpxPriceProto::_internal_items(int index) const {
  return _impl_.items_.Get(index);
}
inline const ::HpXVer::PriceInfo& HpxPriceProto::items(int index) const {
  // @@protoc_insertion_point(field_get:HpXVer.HpxPriceProto.items)
  return _internal_items(index);
}
inline ::HpXVer::PriceInfo* HpxPriceProto::_internal_add_items() {
  return _impl_.items_.Add();
}
inline ::HpXVer::PriceInfo* HpxPriceProto::add_items() {
  ::HpXVer::PriceInfo* _add = _internal_add_items();
  // @@protoc_insertion_point(field_add:HpXVer.HpxPriceProto.items)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::HpXVer::PriceInfo >&
HpxPriceProto::items() const {
  // @@protoc_insertion_point(field_list:HpXVer.HpxPriceProto.items)
  return _impl_.items_;
}

// -------------------------------------------------------------------

// HpxTheoProgressProto

// repeated .HpXVer.TheoProgress items = 1;
inline int HpxTheoProgressProto::_internal_items_size() const {
  return _impl_.items_.size();
}
inline int HpxTheoProgressProto::items_size() const {
  return _internal_items_size();
}
inline void HpxTheoProgressProto::clear_items() {
  _impl_.items_.Clear();
}
inline ::HpXVer::TheoProgress* HpxTheoProgressProto::mutable_items(int index) {
  // @@protoc_insertion_point(field_mutable:HpXVer.HpxTheoProgressProto.items)
  return _impl_.items_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::HpXVer::TheoProgress >*
HpxTheoProgressProto::mutable_items() {
  // @@protoc_insertion_point(field_mutable_list:HpXVer.HpxTheoProgressProto.items)
  return &_impl_.items_;
}
inline const ::HpXVer::TheoProgress& HpxTheoProgressProto::_internal_items(int index) const {
  return _impl_.items_.Get(index);
}
inline const ::HpXVer::TheoProgress& HpxTheoProgressProto::items(int index) const {
  // @@protoc_insertion_point(field_get:HpXVer.HpxTheoProgressProto.items)
  return _internal_items(index);
}
inline ::HpXVer::TheoProgress* HpxTheoProgressProto::_internal_add_items() {
  return _impl_.items_.Add();
}
inline ::HpXVer::TheoProgress* HpxTheoProgressProto::add_items() {
  ::HpXVer::TheoProgress* _add = _internal_add_items();
  // @@protoc_insertion_point(field_add:HpXVer.HpxTheoProgressProto.items)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::HpXVer::TheoProgress >&
HpxTheoProgressProto::items() const {
  // @@protoc_insertion_point(field_list:HpXVer.HpxTheoProgressProto.items)
  return _impl_.items_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace HpXVer

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_hpx_2eproto
